$terminal = kitty -c ~/.config/hypr/kitty/kitty.conf
$editor = $terminal nvim
$browser = firefox
$fileManager = dolphin
$menu = rofi -config ~/.config/hypr/rofi/apps.rasi
$youtube = $browser --new-window https://www.youtube.com/
$video_player = mpv
