source = ~/.config/hypr/hyprland/colors.conf

$CITY = Agadir
$COUNTRY = Morocco

background {
    monitor =
    path = ~/.config/hypr/wallpapers/screenshot.png
    blur_passes = 3
    blur_size = 4
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
    ignore_empty_input = true
}

# hour
label {
    shadow_passes = 1
    shadow_boost = 0.5
    monitor = 
    text = cmd[update:1000] echo "<span>$(date +"%H")</span>"
    color = $primary_fixed
    font_size = 200
    font_family = NotoSerif Bold
    position = 0, 300
    halign = center
    valign = center
}

# mins
label {
    shadow_passes = 1
    shadow_boost = 0.5
    monitor = 
    text = cmd[update:1000] echo "<span>$(date +"%M")</span>"
    color = $primary_fixed
    font_size = 200
    font_family = NotoSerif Bold
    position = 0, 80
    halign = center
    valign = center
}


label {
    shadow_passes = 1
    shadow_boost = 0.5
    text = cmd[update:1000] echo "<span>$(date +"%B %d, %Y")</span>"
    color = $primary_fixed
    font_size = 20
    font_family = JetBrainsMonoNerdFont
    position = 0, -60
    halign = center
    valign = center
}


label {
    shadow_passes = 1
    shadow_boost = 0.5
    monitor =
    text = cattooo@MidnightChannel
    color = $tertiary
    font_size = 18
    font_family = JetBrainsMono
    position = 18, -10
    halign = left
    valign = top
}








label {
    shadow_passes = 1
    shadow_boost = 0.5
    monitor =
    text = "What a week, huh?"
    color = $on_secondary_container
    font_size = 12
    font_family = JetBrainsMono
    position = 0, -180
    halign = center
    valign = center
}

label {
    shadow_passes = 1
    shadow_boost = 0.5
    text = cmd[update:1000] echo "<span>Cattooo, it's $(date +"%A")...</span>"
    color = $on_secondary_container
    font_size = 12
    font_family = JetBrainsMono
    position = 0, -200
    halign = center
    valign = center
}

# spotify
label {
    shadow_passes = 1
    shadow_boost = 0.5
    monitor = 
    text = cmd[update:1000] echo "$(~/.config/hypr/scripts/spotify.sh)"
    color = $tertiary
    font_size = 18
    font_family = JetBrainsMono
    position = 0, 5
    halign = center
    valign = bottom
}

# weather
label {
    shadow_passes = 1
    shadow_boost = 0.5
    monitor = 
    text = cmd[update:1000] echo "$(bash ~/.config/hypr/scripts/lockweather.sh)"
    color = $tertiary
    font_size = 18
    font_family = JetBrainsMono
    position = -20, -10
    halign = right
    valign = top
}


input-field {
    monitor =
    size = 320, 55
    outline_thickness = 3
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.3 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = $inverse_primary
    inner_color = rgba(0,0,0,0.1)
    font_color = $inverse_primary
    fade_on_empty = true
    font_family = JetBrainsMono
    placeholder_text = 
    hide_input = false
    position = 0, -250
    halign = center
    valign = center
}
