exec-once = swaync -s ~/.config/hypr/swaync/style.css -c ~/.config/hypr/swaync/config.json
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = hyprlock -c ~/.config/hypr/hyprland/hyprlock.conf
exec-once = waybar -c ~/.config/hypr/waybar/config -s ~/.config/hypr/waybar/style.css
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-clip-persist --clipboard regular
exec-once = swww-daemon &
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = systemctl start iwd